# run: conda env create --file environment.yml
name: ektar-pelican
dependencies:
- anaconda
- beautifulsoup4
- flake8
- ipython
- ipython[notebook]
- Markdown
- matplotlib
- nbconvert
- numpy
- pandas
- pelican
- pip
- python>=3.5
