# run: conda env create --file environment.yml
name: ektar-pelican
dependencies:
- anaconda
- beautifulsoup4
- flake8
- ipython
- jupyter
- Markdown
- matplotlib
- nbconvert
- numpy
- pandas
- pip
- python>=3.5
- pyzmq
- pip:
  - disqus-python
  - pelican>=3.7
  - python-gettext
  - typogrify