# run: conda env create --file environment.yml
name: ektar-pelican
dependencies:
- anaconda
- beautifulsoup4
- flake8
- ipython
- Markdown
- matplotlib
- nbconvert
- numpy
- pandas
- pip
- python>=3.5
- pip:
  - disqus-python
  - pelican
  - typogrify