# -*- coding: utf-8 -*- #

BOOTSTRAP_THEME = 'readable'
#BOOTSTRAP_NAVBAR_INVERSE = True
BOOTSTRAP_FLUID = True
DISPLAY_BREADCRUMBS = True
DISPLAY_CATEGORY_IN_BREADCRUMBS = True
DISPLAY_ARTICLE_INFO_ON_INDEX = True

SHOW_ARTICLE_AUTHOR = True
SHOW_DATE_MODIFIED = True
SHOW_ARTICLE_CATEGORY = True

DISPLAY_TAGS_ON_SIDEBAR = True

USE_OPEN_GRAPH = False

CUSTOM_CSS = 'custom.css'
PYGMENTS_STYLE = 'monokai'

DISPLAY_CATEGORIES_ON_MENU = True
DISPLAY_PAGES_ON_MENU = True

DEFAULT_CATEGORY = "General"

DISPLAY_SERIES_ON_SIDEBAR = True

GOOGLE_ANALYTICS_UNIVERSAL = 'UA-89492841-1'
GOOGLE_ANALYTICS_UNIVERSAL_PROPERTY = 'auto'
